version: "3.8"

services:
  app:
    container_name: orthopedic_spine_service_app
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
        APP_ENV: container
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    container_name: orthopedic_spine_service_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: orthopedic_spine_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:

  # run
 #  docker-compose up --build

