version: "3.8"

services:
  app:
    container_name: orthopedic_spine_service
    build:
      context: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - ${PWD}/.env
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/orthopedic_spine_db
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orthopedic_spine_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:

  # run
 #  docker-compose up --build

