app:
  name: "Orthopedic Spine Service"
  debug: false

postgres:
  username: "clinicAdmin"
  password: !ENV ${POSTGRES_PASSWORD}
  host: "clinic-db.c0jqq40k641n.us-east-1.rds.amazonaws.com"
  port: 5432
  dbname: "clinic-db"
  echo: false  # SQLAlchemy echo logs

email:
  smtpServer: "smtp.gmail.com"
  smtpPort: 465
  address: "orthopedicspineinfo@gmail.com"
  password: !ENV ${EMAIL_PASSWORD}

authentication:
  secretKey: !ENV ${SECRET_KEY}
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
