app:
  name: "Orthopedic Spine Service"
  debug: true

postgres:
  username: "admin"
  password: !ENV ${POSTGRES_PASSWORD}
  host: "localhost"
  port: 5432
  dbname: "orthopedic_spine_db"
  echo: false  # SQLAlchemy echo logs

email:
  smtpServer: "smtp.gmail.com"
  smtpPort: 465
  address: "orthopedicspineinfo@gmail.com"
  password: !ENV ${EMAIL_PASSWORD}


authentication:
  secretKey: !ENV ${SECRET_KEY}
  algorithm: "HS256"
  access_token_expire_minutes: 30
