app:
  name: "Orthopedic Spine Service"
  debug: false

postgres:
  username: "admin"
  password: !ENV ${POSTGRES_PASSWORD}
  host: "postgres"
  port: 5432
  dbname: "orthopedic_spine_db"
  echo: false  # SQLAlchemy echo logs

email:
  address: "orthopedicspineinfo@gmail.com"
  password: !ENV ${EMAIL_PASSWORD}

